// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unique_key_query.proto

package io.grpc;

public interface UniKeyQueReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UniKeyQueReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uniKeyVal = 1;</code>
   */
  java.lang.String getUniKeyVal();
  /**
   * <code>string uniKeyVal = 1;</code>
   */
  com.google.protobuf.ByteString
      getUniKeyValBytes();
}
