// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unique_key_query.proto

package io.grpc;

public interface UniKeyQueRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UniKeyQueResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool uniKeyExi = 1;</code>
   */
  boolean getUniKeyExi();
}
