// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unique_key_query.proto

package io.grpc;

public final class UniKeyQue {
  private UniKeyQue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UniKeyQueReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UniKeyQueReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UniKeyQueResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UniKeyQueResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026unique_key_query.proto\"!\n\014UniKeyQueReq" +
      "\022\021\n\tuniKeyVal\030\001 \001(\t\"\"\n\rUniKeyQueResp\022\021\n\t" +
      "uniKeyExi\030\001 \001(\0102A\n\014UniKeyQueSrv\0221\n\016query" +
      "UniqueKey\022\r.UniKeyQueReq\032\016.UniKeyQueResp" +
      "\"\000B\026\n\007io.grpcB\tUniKeyQueP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UniKeyQueReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UniKeyQueReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UniKeyQueReq_descriptor,
        new java.lang.String[] { "UniKeyVal", });
    internal_static_UniKeyQueResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UniKeyQueResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UniKeyQueResp_descriptor,
        new java.lang.String[] { "UniKeyExi", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
